name: ci

on:
  push:
    branches:
    - main
  schedule:
    - cron: "* 18 * * *"
    
jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "1597344758@qq.com"
          git config --local user.name "HshousHe"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.DAY_TOKEN }}@github.com/${{ github.repository }} 
          git pull --rebase
          git commit --allow-empty -m ":white_check_mark: 今天 又是充满希望的一天呢"
          git push
